### ISSUE TITLE
Needs updating for pythondata* submodules

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-i2s-demo#1]
Hi, I had noticed that Litex had switched things around to start using pythondata*  submodules.   It seems the configuration here needs a bit of updating to match, or else, it should point to an older version of Litex.

When I follow the instructions, I encounter this:
```
Traceback (most recent call last):
  File "/home/tim/antmicro/zephyr-on-litex-vexriscv/third_party/litex/litex/__init__.py", line 10, in get_data_mod
    exec(imp, {}, l)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pythondata_cpu_vexriscv'
```

In `third_party/litex`, I am at `a39660fa99b27b765e9115dcd3c77fde53db5906` (Sept 17).

**Comment by mateusz-holenko** [comment]
Hi @tcal-x,

Thanks for reporting the issue!
I can confirm that two submodules are currently missing: `pythondata-cpu-vexrisv` and `pythondata-software-compiler_rt`.
I prepared a fix at: https://github.com/antmicro/zephyr-on-litex-vexriscv/tree/add_missing_repos and we are testing it on HW.

**Comment by mateusz-holenko** [comment]
I guess this one is already fixed.
