### ISSUE TITLE
Instructions out of sync with repo

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-i2s-demo#2]
The README instructions don't seem to match the current repo contents.

The repo has submodules for 
-  git@github.com:zephyrproject-rtos/zephyr.git
-  git@github.com:antmicro/zephyr-on-litex-vexriscv.git

but the instructions tell you to do a `git clone` of zephyr-on-litex-vexrisc, rather than doing a submodule update.

Also, it's not clear which parts of the "tutorial" at https://github.com/antmicro/zephyr-on-litex-vexriscv-build you're supposed to do to set up the Zephyr.   Are you supposed to clone that repo as well?   It tells you to build LiteX gateware again.  I think it would be easier to understand if you add whatever setup instructions are necessary right here,instead of pointing at another repo, and then give instructions how to use the zephyr submodule to build the i2s demo.

**Comment by mateusz-holenko** [comment]
@tcal-x `README` is now rewritten to address your comments - what do you think about the current version?
