### ISSUE TITLE
Some packages missing with new instructions

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-i2s-demo#3]
I encountered `No module named..` errors ("dateutil" and "elftools") and had to manually install the following:

```
pip3 install python-dateutil
pip3 install pyelftools
```

Are necessary installs supposed to be done by `./build_i2s_zephyr.sh` ?

In my search trying to figure out what I needed to install, I noticed this:
https://github.com/zephyrproject-rtos/zephyr/issues/1392

**Comment by mateusz-holenko** [comment]
@tcal-x we updated `README` and `build_i2s_zephyr.sh` files - could you check if it works for you now?
