### ISSUE TITLE
Bump submodule zephyr-on-litex-vexriscv?

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-i2s-demo#4]
This repo is using zephyr-on-litex-vexriscv pinned at its very first commit.   There have been quite a few updates in that repo; do you want to bump the reference from here to a more recent commit?

**Comment by mateusz-holenko** [comment]
The `zephyr-on-litex-vexriscv` submodule is now bumped and targets the most recent commit.
